
name: main
on: push
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run:      sudo mkdir log2 & echo 'hello' tee /log2/hello.log > sudo
        working-directory: ../
  job2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2 
      
      
