
name: main
on: push
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
         curl -o test.xml https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/kotlin/kotlin-compiler/maven-metadata.xml
         curl www.tecmint.com
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
           # Artifact name
          name:  drop1
           # Directory containing files to upload
          path: ${{ Github.workspace }}
         
