
name: main
on: push
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run:  |
               sudo mkdir -p /home/azure/actions-runner/_work/shorturls/log4
               sudo touch /home/azure/actions-runner/_work/shorturls/log4/text123.txt
               chmod -R 757 /home/azure/actions-runner/_work/shorturls/
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
         name: drop1
         path: /home/azure/actions-runner/_work/shorturls
  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      
      
