
name: main
on: push
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
           sudo mkdir log
           echo 'hello' tee /log/hello.log > sudo
        working-directory: ../
      
