
name: main
on: push
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
         curl -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/kotlin/kotlin-compiler/maven-metadata.xml
         curl www.tecmint.com

         
