
name: main
on: push
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run:  |
               sudo mkdir -p /home/azure/actions-runner/_work/shorturls/log5
               sudo touch /home/azure/actions-runner/_work/shorturls/log5/text123.txt
             

  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      
      
