
name: main
on: push
   
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         curl https://dl.bintray.com/kotlin/kotlin-dev/org/jetbrains/kotlin/kotlin-compiler/maven-metadata.xml
      
